# Generated by Django 5.0.1 on 2024-03-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccounttasks_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounttasks',
            name='task_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
